services:
  app:
    build: .
    container_name: wgparser
    image: neero711/wgparser:1.0
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - npm-network

  proxy:
    image: jc21/nginx-proxy-manager
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    depends_on:
      - app
    networks:
      - npm-network
volumes:
  npm_data:
  npm_letsencrypt:

networks:
  npm-network:
    driver: bridge